### ISSUE TITLE
Has no exported member 'CampaignAction'

### ISSUE THREAD

**Issue by rmalkevy** [zygos/mailerlite-api-v2-node#10]
I am trying to build express.js app and got this error.

node_modules/mailerlite-api-v2-node/dist/index.d.ts:48:66 - error TS2694: Namespace '"/Users/henprokuror/VS_Code/Datrics/backend/node_modules/mailerlite-api-v2-node/dist/@types/index"' has no exported member 'CampaignAction'.

48     actOnCampaign(campaignId: number, action: import("./@types").CampaignAction, data?: import("./@types").CampaignSendData): Promise<import("axios").AxiosResponse<any>>;

"mailerlite-api-v2-node": ^1.0.2
![Screenshot 2020-10-22 at 15 15 12](https://user-images.githubusercontent.com/19776637/96871785-68fee400-147b-11eb-8420-69a74e4e26f5.png)
![Screenshot 2020-10-22 at 15 14 56](https://user-images.githubusercontent.com/19776637/96871789-6ac8a780-147b-11eb-9eca-3ef98a2d02d8.png)

**Comment by zygos** [comment]
Thanks for the report. Fixed this in 1.1.1 release. Please verify it resolved your issue.

**Comment by rmalkevy** [comment]
@zygos  Yes !!!! It works now, thank you)
