### ISSUE TITLE
City and company should be optional in SubscriberFields

### ISSUE THREAD

**Issue by mkupiniak** [zygos/mailerlite-api-v2-node#9]
Hi,

currently you have such an interface: (before)
```
export interface SubsriberFields {
  city: string
  company: string
  [key: string]: any
}
```

I think this interface should look like this: (after)
```
export interface SubsriberFields {
  [key: string]: string | number | Date
}
```

since only these types are allowed and field can be any string.

**Comment by zygos** [comment]
Hi,

thanks for the suggestion. Adopted it in v1.1 release 👍 

Also fixed Sub**sr**iberFields typo 😅
